name: Refresh data

env:
  PYTHONIOENCODING: utf-8

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  
jobs:
  main:
    runs-on: windows-latest
    permissions:
      contents: write # committing
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          path: ipa-track

      - name: Checkout ipatool-py
        uses: actions/checkout@v4.2.2
        with:
          repository: NyaMisty/ipatool-py
          path: ipatool-py
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -r requirements.txt
        working-directory: ipatool-py
      - name: Setup iTunes Header Service
        uses: NyaMisty/actions-iTunes-header@master
        with:
          apple_id: ${{ secrets.EMAIL }}
          apple_id_pwd: ${{ secrets.PASSWORD }}
          ngrok_token: ${{ secrets.NGROK_AUTH_TOKEN }}
        
      - name: Execute operation
        id: operation
        run: |
          mkdir ipaDown
          for dir in ipa-track/*/; do
            dir_name=$(basename "$dir")
            output=$(python3 ipatool-py/main.py --json lookup -b "$dir_name" -c AU download -o ipaDown -s http://127.0.0.1:9000)
            echo "Got Downloading JSON result for $dir_name: $output"
            python3 ipa-track/main.py --appBundleId "ipa-track/$dir_name" --downloadedIPA "$(echo "$output" | jq -r '.downloadedIPA')"
          done
        shell: bash

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: Change detected
          cwd: ipa-track
